### ISSUE TITLE
new AjaxCallBack<File>()    onLoading方法不执行,只执行onSuccess方法,什么问题?

### ISSUE THREAD

**Issue by SmallPlate** [yangfuhai/afinal#92]
public void onLoading(long count,long current){};
public void onSuccess(T t){};
public void onFailure(Throwable t,int errorNo ,String strMsg){};

**Comment by bacy** [comment]
你是下载方法吗？文件有多大？

**Comment by panda-baby** [comment]
FinalHttp http = new FinalHttp();

					http.download(path,
							Environment.getExternalStorageDirectory()
									+ "/mobile2.0.apk",
							new AjaxCallBack<File>() {

								@Override
								public void onFailure(Throwable t, int errorNo,
										String strMsg) {
									Toast.makeText(getApplicationContext(),
											"下载失败", 1).show();
									
									t.printStackTrace();
									super.onFailure(t, errorNo, strMsg);
								}

								@Override
								public void onLoading(long count, long current) {
									super.onLoading(count, current);
									
									tv_splash_updateinfo
											.setVisibility(View.VISIBLE);
								
									int progress = (int) (current * 100 / count);
								
									tv_splash_updateinfo.setText("下载进度:"
											+ progress + "%");
								}

								@Override
								public void onSuccess(File t) {
									super.onSuccess(t);
									installApk(t);
								}

**Comment by panda-baby** [comment]
onSuccess方法执行了,但是onLoading方法没执行

**Comment by javaDashuaiAndroid** [comment]
dHttp.download(
				"http://yinyueshiting.baidu.com/data2/music/124383790/124380645248400128.mp3?xcode=2f36611e0d3ba556dd6ee9dbca2422d52f7167fd0a01384c",
				DFileUtil.getExternalStorageDirectory() + "/congcongnanian.mp3",
				new AjaxCallBack<File>() {

					public void onSuccess(File t) {

						Toast.makeText(DHttpActivity.this,
								"歌曲下载完成，路径是" + t.getAbsolutePath(),
								Toast.LENGTH_SHORT).show();
					};

					public void onLoading(long count, long current) {

						textView.setText("正在下载： "
								+ (int) (((float) (current * 1.0) / count * 1.0) * 100)
								+ " %");

					};

					public void onFailure(Throwable t, int errorNo,
							String strMsg) {

						t.printStackTrace();

						Toast.makeText(DHttpActivity.this, "歌曲下载失败",
								Toast.LENGTH_SHORT).show();
					};

				}.progress(true, 1000));

.progress(true, 1000));

**Comment by panda-baby** [comment]
Solved, thank you
